export enum SupportedNats {
	AU = "AU",
	BR = "BR",
	CA = "CA",
	CH = "CH",
	DE = "DE",
	ES = "ES",
	FI = "FI",
	FR = "FR",
	GB = "GB",
	IE = "IE",
	IN = "IN",
	IR = "IR",
	MX = "MX",
	NL = "NL",
	NO = "NO",
	RS = "RS",
	TR = "TR",
	UA = "UA",
	US = "US",
}

export const SupportedNatsMap: Record<SupportedNats, string> = {
	[SupportedNats.AU]: "Australia",
	[SupportedNats.BR]: "Brazil",
	[SupportedNats.CA]: "Canada",
	[SupportedNats.CH]: "Switzerland",
	[SupportedNats.DE]: "Germany",
	[SupportedNats.ES]: "Spain",
	[SupportedNats.FI]: "Finland",
	[SupportedNats.FR]: "France",
	[SupportedNats.GB]: "United Kingdom",
	[SupportedNats.IE]: "Ireland",
	[SupportedNats.IN]: "India",
	[SupportedNats.IR]: "Iran",
	[SupportedNats.MX]: "Mexico",
	[SupportedNats.NL]: "Netherlands",
	[SupportedNats.NO]: "Norway",
	[SupportedNats.RS]: "Serbia",
	[SupportedNats.TR]: "Turkey",
	[SupportedNats.UA]: "Ukraine",
	[SupportedNats.US]: "United States",
};
